language: go

os:
  - linux
  - osx

before_install:
 - if [ "$TRAVIS_OS_NAME" = 'osx' ]; then
     brew update;
     brew install readline;
     brew install cmake;
   fi;

addons:
  apt:
    packages:
      - libncurses5-dev
      - libncursesw5-dev
      - libreadline-dev
      - libgit2-dev

script:
  - make test
