name: grv
version: master
summary: Terminal interface for viewing git repositories
description: |
        GRV is a terminal based interface for viewing git repositories.
        It allows refs, commits and diffs to be viewed, searched and filtered.
        The behaviour and style can be customised through configuration.
        A query language can be used to filter refs and commits.
confinement: classic
grade: devel

apps:
        grv:
                command: bin/grv
                environment:
                        LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu

# The configuration below is adapted from the Micro text editor snapcraft.yaml
# Copyright (c) 2016-2017 Zachary Yedidia, et al.
parts:
        grv:
                source: .
                source-type: git
                plugin: nil
                build-packages:
                        - golang-go
                        - make
                        - build-essential
                        - pkg-config
                        - cmake
                        - libncurses5-dev
                        - libncursesw5-dev
                        - libreadline-dev
                        - libssh2-1-dev
                        - libhttp-parser-dev
                prepare: |
                        mkdir -p ../go/src/github.com/rgburke/grv
                        cp -fr . ../go/src/github.com/rgburke/grv
                build: |
                        export GOPATH=$(pwd)/../go
                        export GOBIN=$(pwd)/../go/bin
                        cd ../go/src/github.com/rgburke/grv
                        make install
                install: |
                        mkdir -p $SNAPCRAFT_PART_INSTALL/bin
                        mv ../go/bin/grv $SNAPCRAFT_PART_INSTALL/bin/
